[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-unknown-none"

[target.'cfg(target_os = "none")']
# Limage compatibility with `cargo run`
runner = "cargo qemu-runner"
# Required for Cargo to pass the correct flags to the linker before running `limage runner`
rustflags = ["-C", "relocation-model=static", "-C", "code-model=kernel"]

